// FILE: pubspec.yaml
name: workout_tracker
description: Workout Tracker app
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  get_it: ^7.6.0
  provider: ^6.0.5
  intl: ^0.18.0
  table_calendar: ^3.0.9
  uuid: ^3.0.6
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0
  cached_network_image: ^3.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
